- name: Variables to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "140 HRS"
    TRAINER: "SivaKumar Reddy"
  tasks: 
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi..! I'm learning {{COURSE}} , Duration is: {{DURATION}} , and my Trainer is: {{TRAINER}}"