- name: Variables from inventory
  hosts: web
  tasks:
  - name: print the ongoing course information
    ansible.builtin.debug:
      msg: "Hi... I'm learning {{COURSE}} , Duration is: {{DURATION}} and my Trainer is:{{TRAINER}}"

      