- name: check the number is less than or greater than 10
  hosts: web
  vars_prompt:
  - name: my_number
    prompt: please enter the number
    private: false # not confidential
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less than 10"
    when: my_number | int < 10

  - name: print this if greater than 10
    ansible.builtin.debug:
      msg: "Given number {{my_number }} is greater than 10"
    when: my_number | int >= 10
