- name: loops demo - print the names
  hosts: web
  become: yes
  tasks:
  - name: print the names
    ansible.builtin.debug:
      msg: "This is {{ item }} my family"
    loop:
    - Lakshmi
    - Dastagiri
    - Dinesh
    - Karthiki
    - Digvijay
    - Annanya Mokksha
    - Spike
    