- name: Demo on filters/functions
  hosts: web
  become: yes
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "HELLO {{ course | default ('AWS') }}"

  - name: convert to upper case
    vars:
      greeting: "Hello Amma"
    ansible.builtin.debug:
      msg: "{{ greeting | upper}}"

  - name: convert to lower case
    vars:
      greeting: "Hi Nanna"
    ansible.builtin.debug:
      msg: "{{ greeting | lower}}"
      