- name: Demo on filters/functions
  hosts: web
  become: yes
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "HELLO {{ course | default ('AWS') }}"

  - name: convert to upper case
    vars:
      greeting: "Hello Amma"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: convert to lower case
    vars:
      greeting: "Hi Nanna"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"
  
  - name: get the unique value
    vars:
      numbers: [2,3,4,4,5,6,6,43,45,45,9]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: get the min and max 
    vars:
      numbers: [ 88,8,6,2,34,45,1,0,2,3,78,99,143,9999 ]
    ansible.builtin.debug:
      msg: " Min: {{ numbers | min }} , Max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course:
        name: "DevOps with AWS"
        duration: 120
        trainer: "SIVAKUMAR"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
      - { "key": "name" , "value": "DevOps with AWS" }
      - { "key": "duration" , "value": 120 }
      - { "key": "trainer" , "value": "SIVAKUMAR" }
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"  


