- name: create ec2 and r53 records
  hosts: local
  connection: local
 # become: yes
  vars:
    subnet_id: "subnet-003aa0c858f31d196"
    sg_id: "sg-048c74456592b8877"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
  zone: harshadaws81s.online
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance: # module
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: "t3.micro"
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
    loop: "{{instances}}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ec2_instances}}"

  - name: create r53 
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
      
    loop: "{{ec2_instances.results}}"


   
